{"uuid": "7d0de8cb-1668-427a-b682-2d7afe2c3590", "children": ["965cdf53-1bd0-4df2-9d77-16431f26e828", "a1f2a30b-ec60-4ef1-bcea-a033f8d26d83", "e2e683f9-4422-4551-88b5-99dd0af5cf26"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 93, in start\n    self._start_process(self._path)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 209, in _start_process\n    raise WebDriverException(\n"}, "start": 1718676682672, "stop": 1718676684759}], "start": 1718676682672, "stop": 1718676684799}