{"uuid": "512f2e72-8c5d-4f3c-a8c8-6bebfa8fd9cd", "children": ["eafca563-3492-4bc3-8ee5-a6ed2c03c694", "bada6f6c-b0c4-4ae8-8a2f-5467a88882bb", "c05cd701-1440-4e70-a3b9-448c7795c80b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 93, in start\n    self._start_process(self._path)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 209, in _start_process\n    raise WebDriverException(\n"}, "start": 1718677590765, "stop": 1718677592604}], "start": 1718677590765, "stop": 1718677592651}