{"uuid": "c2fef3a7-eb41-43f0-bc6f-168d3c0bc808", "children": ["7d1a2a11-6cf4-491f-ad44-32f7563dc510", "ec76d217-778d-4da3-9566-181df0e33c84", "e24914e5-c9fb-4b6a-8633-158ca34ea18d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 93, in start\n    self._start_process(self._path)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 209, in _start_process\n    raise WebDriverException(\n"}, "start": 1718676617789, "stop": 1718676620066}], "start": 1718676617789, "stop": 1718676620122}