{"uuid": "8a70394d-acdd-434c-9987-f97dfc8b3444", "children": ["3d4e4d59-4569-4a2f-b4be-a3447273b985", "afac7f6e-0954-4e0e-932c-ab291e030272", "a3de0b14-79e0-4ff0-a1a5-9204c51d2ec3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 93, in start\n    self._start_process(self._path)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py\", line 209, in _start_process\n    raise WebDriverException(\n"}, "start": 1718678132840, "stop": 1718678134685}], "start": 1718678132840, "stop": 1718678134725}